# Generated by Django 3.1 on 2022-12-28 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_reviewerating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevieweRating',
            new_name='ReviewRating',
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100),
        ),
    ]
