# Generated by Django 3.1 on 2022-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221205_1538'),
        ('carts', '0002_cartiem_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartIem',
            new_name='CartItem',
        ),
    ]
