# Generated by Django 3.1 on 2022-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221205_1538'),
        ('carts', '0003_auto_20221206_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartIem',
        ),
    ]
