# Generated by Django 3.1 on 2022-12-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20221206_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartiem',
            old_name='variation',
            new_name='variations',
        ),
    ]
